/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ShopBasketRouteImport } from './routes/shop/basket'
import { Route as ShopListingIdRouteImport } from './routes/shop/$listingId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ShopCheckoutSuccessRouteImport } from './routes/shop/checkout/success'
import { Route as ShopCheckoutCancelRouteImport } from './routes/shop/checkout/cancel'
import { Route as BlogTagTagRouteImport } from './routes/blog/tag.$tag'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBasketRoute = ShopBasketRouteImport.update({
  id: '/shop/basket',
  path: '/shop/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopListingIdRoute = ShopListingIdRouteImport.update({
  id: '/shop/$listingId',
  path: '/shop/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutSuccessRoute = ShopCheckoutSuccessRouteImport.update({
  id: '/shop/checkout/success',
  path: '/shop/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutCancelRoute = ShopCheckoutCancelRouteImport.update({
  id: '/shop/checkout/cancel',
  path: '/shop/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/blog/tag/$tag',
  path: '/blog/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/shop/$listingId': typeof ShopListingIdRoute
  '/shop/basket': typeof ShopBasketRoute
  '/blog/': typeof BlogIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/shop/$listingId': typeof ShopListingIdRoute
  '/shop/basket': typeof ShopBasketRoute
  '/blog': typeof BlogIndexRoute
  '/shop': typeof ShopIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/shop/$listingId': typeof ShopListingIdRoute
  '/shop/basket': typeof ShopBasketRoute
  '/blog/': typeof BlogIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/shop/checkout/cancel': typeof ShopCheckoutCancelRoute
  '/shop/checkout/success': typeof ShopCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/returns-policy'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/shop/$listingId'
    | '/shop/basket'
    | '/blog/'
    | '/shop/'
    | '/blog/tag/$tag'
    | '/shop/checkout/cancel'
    | '/shop/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/returns-policy'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/shop/$listingId'
    | '/shop/basket'
    | '/blog'
    | '/shop'
    | '/blog/tag/$tag'
    | '/shop/checkout/cancel'
    | '/shop/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/returns-policy'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/shop/$listingId'
    | '/shop/basket'
    | '/blog/'
    | '/shop/'
    | '/blog/tag/$tag'
    | '/shop/checkout/cancel'
    | '/shop/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ShopListingIdRoute: typeof ShopListingIdRoute
  ShopBasketRoute: typeof ShopBasketRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
  ShopCheckoutCancelRoute: typeof ShopCheckoutCancelRoute
  ShopCheckoutSuccessRoute: typeof ShopCheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/basket': {
      id: '/shop/basket'
      path: '/shop/basket'
      fullPath: '/shop/basket'
      preLoaderRoute: typeof ShopBasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$listingId': {
      id: '/shop/$listingId'
      path: '/shop/$listingId'
      fullPath: '/shop/$listingId'
      preLoaderRoute: typeof ShopListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/success': {
      id: '/shop/checkout/success'
      path: '/shop/checkout/success'
      fullPath: '/shop/checkout/success'
      preLoaderRoute: typeof ShopCheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/cancel': {
      id: '/shop/checkout/cancel'
      path: '/shop/checkout/cancel'
      fullPath: '/shop/checkout/cancel'
      preLoaderRoute: typeof ShopCheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ShopListingIdRoute: ShopListingIdRoute,
  ShopBasketRoute: ShopBasketRoute,
  BlogIndexRoute: BlogIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  BlogTagTagRoute: BlogTagTagRoute,
  ShopCheckoutCancelRoute: ShopCheckoutCancelRoute,
  ShopCheckoutSuccessRoute: ShopCheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
